### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by nkrapivin** [eric-wieser/snakes#11]
C:\Users\Nikita\Desktop\snakes>node server.js 8090
C:\Users\Nikita\Desktop\snakes\node_modules\restler\lib\restler.js:84
Request.prototype = new process.EventEmitter();
                    ^

TypeError: process.EventEmitter is not a constructor
    at Object.<anonymous> (C:\Users\Nikita\Desktop\snakes\node_modules\restler\l
ib\restler.js:84:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Nikita\Desktop\snakes\node_modules\faceplate
\index.js:4:15)
    at Module._compile (module.js:652:30)

C:\Users\Nikita\Desktop\snakes>

**Comment by nkrapivin** [comment]
Fixed. New problem.
C:\Users\Nikita\Desktop\snakes>node server.js 80
C:\Users\Nikita\Desktop\snakes\server.js:29
io.configure('development', function() {
   ^

TypeError: io.configure is not a function
    at Object.<anonymous> (C:\Users\Nikita\Desktop\snakes\server.js:29:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

C:\Users\Nikita\Desktop\snakes>

**Comment by eric-wieser** [comment]
Hmm, probably my fault for not pinning the versions of my dependencies. If you use an old enough version of socket.io, that might go away
